# Generated by Django 4.2.2 on 2023-06-10 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0002_category_alter_card_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='board_app.category'),
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
