# Generated by Django 4.2.2 on 2023-06-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0003_alter_card_category_alter_card_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
